title: Kung Fu Lambda's io
email: leon.tadina@gmail.com
description: ''
baseurl: ''
url: ''
github_username: kungFuLambda
<<<<<<< HEAD
theme: minima
=======
theme: minimal
>>>>>>> 1414b98458a3af34674e499040980ceb06bb430e
plugins:
  - jekyll-feed
